### ISSUE TITLE
Recover when a webdriver dies

### ISSUE THREAD

**Issue by chris-martin** [cardforcoin/shale#21]
We just hit a problem where one dead webdriver took down the whole service.

Workaround for when you need to force delete a session:

```
> redis-cli -h [ redis node ]
redis > KEYS *
{ a whole bunch of keys }
redis > KEYS _shale*
1) "_shale/nodes/c817ef78-2ffe-4d07-9517-9d2bb8a06769"
2) "_shale/sessions/2c4045b1-8435-4ed3-b771-a20e5d906fdb"
3) "_shale/nodes/ea2b3e7a-79d8-4919-965e-d200649fbb43"
4) "_shale/nodes"
5) "_shale/nodes/7102736b-f8b0-4e9e-b1a4-9f9dcff7a5a5"
6) "_shale/sessions"
SREM "_shale/sessions" "2c4045b1-8435-4ed3-b771-a20e5d906fdb"
DEL "_shale/sessions/2c4045b1-8435-4ed3-b771-a20e5d906fdb"
```

We need to add a timeout somewhere so things don't just hang when selenium can't be reached.

**Comment by mhluongo** [comment]
One option https://github.com/flatland/clojail/blob/master/src/clojail/core.clj#L24

**Comment by mhluongo** [comment]
Other ideas http://stackoverflow.com/questions/6694530/executing-a-function-with-a-timeout
