### ISSUE TITLE
When session creation times out...

### ISSUE THREAD

**Issue by chris-martin** [cardforcoin/shale#37]
I just tried to force-create a session. The first three tries timed out, and the fourth succeeded. This brings up some questions:

* Do we need to raise the timeout from 5 seconds?
* Did those three browsers get created?
* Does the selenium node automatically kill its unused sessions eventually?
* Is there a way in selenium for the refresh-sessions action to ask the node for a list of sessions?
* Are we leaking sessions?

**Comment by mhluongo** [comment]
So I think the answers are
* yes, we've raised the timeouts.
* sometimes the browsers get created
* nodes can't be trusted to kill sessions
* yes, we can use the selenium wire protocol for that.
* yes, we're leaking sessions.

As far as solutions, I'm closing this in favor of the more specific #45, #44, and #42.
