### ISSUE TITLE
Optional timeout for session creation (per API call)

### ISSUE THREAD

**Issue by mhluongo** [cardforcoin/shale#41]

**Comment by chris-martin** [comment]
We subsequently talked about having the get-or-create-session call simply return an error code immediately instead of blocking while creating, so I don't think this is necessary anymore.

**Comment by mhluongo** [comment]
You sure? We could make all of it optional (eg `?block=true&timeout=250`). Seems like for some clients (Python?) we'd rather move the complexity to the service.

**Comment by chris-martin** [comment]
It's easier in the application if nothing is blocking, and it's only retry logic.

**Comment by chris-martin** [comment]
The application has to be able to handle 500s anyway. Blocking just means it also has to deal with timeouts.

**Comment by mhluongo** [comment]
As we discussed, it'll only be a 500 if there's a capacity error- otherwise we can do some sort of "come back later" response. Regardless, closing this for #42.

**Comment by chris-martin** [comment]
`5**`, that is

**Comment by mhluongo** [comment]
Right, sorry. 503 seems like the best fit.
